# Generated by Django 4.2.6 on 2023-10-20 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todomodel",
            old_name="titile",
            new_name="title",
        ),
    ]
