# Generated by Django 4.2.6 on 2023-10-22 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_rename_titile_todomodel_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todomodel",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todomodel",
            name="priority",
            field=models.CharField(
                choices=[("danger", "high"), ("warning", "normal"), ("primary", "low")],
                default="danger",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
